export const COLOURS = {
  primaryBackground: 'antiquewhite',
  secondaryBackground: 'rebeccapurple',
  primaryText: 'rebeccapurple',
  secondaryText: '#8040bf',
  linkText: 'green',
  warningText: '#ba1745',
  successText: 'green',
  errorText: '#ba1745',
  cancelText: '#ba1745',
  placeholderText: '#8040bf',
  primaryButtonBackground: 'rebeccapurple',
  secondaryButtonBackground: 'green',
  buttonText: 'antiquewhite',
  inputBorder: '#8040bf',
  noteItemBackground: 'rgba(128, 64, 191, 0.1)',
  editNoteText: '#007380',
  modalOverlay: 'rgba(0, 128, 0, 0.3)',
  modalContentBackground: 'white',
  modalInputBorder: 'green',
  modalTitle: 'green',
  modalPlaceholderText: '#99CC99',
};
