export const LIGHT_THEME = {
  primaryBackground: 'antiquewhite',
  secondaryBackground: 'rebeccapurple',
  primaryText: 'rebeccapurple',
  secondaryText: '#8040bf',
  linkText: 'green',
  warningText: '#ba1745',
  successText: 'green',
  errorText: '#ba1745',
  cancelText: '#ba1745',
  placeholderText: '#8040bf',
  primaryButtonBackground: 'rebeccapurple',
  secondaryButtonBackground: 'green',
  buttonText: 'antiquewhite',
  inputBorder: '#8040bf',
  noteItemBackground: 'rgba(128, 64, 191, 0.1)',
  editNoteText: '#007380',
  modalOverlay: 'rgba(0, 128, 0, 0.3)',
  modalContentBackground: 'white',
  modalInputBorder: 'green',
  modalTitle: 'green',
  modalPlaceholderText: '#99CC99',
  activityIndicator: 'rebeccapurple',
  headerTintColor: 'antiquewhite',
  headerButtonText: 'rebeccapurple',
};

export const DARK_THEME = {
  primaryBackground: '#121212',
  secondaryBackground: '#1e1b2e',
  primaryText: '#f3eaff',
  secondaryText: '#cbb4f3',
  linkText: '#5CFF8F',
  warningText: '#ff4d7a',
  successText: '#5CFF8F',
  errorText: '#ff4d7a',
  cancelText: '#ff4d7a',
  placeholderText: '#8e79b7',
  primaryButtonBackground: '#6f42c1',
  secondaryButtonBackground: '#1db954',
  buttonText: '#121212',
  inputBorder: '#6f42c1',
  noteItemBackground: 'rgba(111, 66, 193, 0.18)',
  editNoteText: '#00c2a8',
  modalOverlay: 'rgba(0, 0, 0, 0.65)',
  modalContentBackground: '#1e1b2e',
  modalInputBorder: '#1db954',
  modalTitle: '#5CFF8F',
  modalPlaceholderText: '#7bdc9a',
  activityIndicator: '#6f42c1',
  headerTintColor: '#f3eaff',
  headerButtonText: '#f3eaff',
};

export function getThemeForScheme(colorScheme) {
  return colorScheme === 'dark' ? DARK_THEME : LIGHT_THEME;
}
